buildscript {
    ext.kotlin_version = '2.3.21'

    repositories {
        maven { url 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/apache-snapshots' }
        gradlePluginPortal()
        mavenCentral()
        google()
        maven { url "https://jitpack.io" }
        maven { url 'https://developer.huawei.com/repo/' }
        maven { url 'https://mvn.4399doc.com/repository/maven-releases/' }
        maven { url 'https://mvn.4399doc.com/repository/maven-snapshots/' }
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.gradleup.shadow:shadow-gradle-plugin:9.0.0-beta8'
    }
}

wrapper {
    distributionType Wrapper.DistributionType.ALL
}

subprojects {
    version = "3.3.2-SNAPSHOT"

    configurations.all {
        // Projects are using snapshot dependencies that may update more often than 24 hours.
        resolutionStrategy {
            cacheChangingModulesFor 0, 'seconds'
        }
    }
}
