apply plugin: 'java'
apply plugin: 'com.gradleup.shadow'

group = 'org.greenrobot'
// this artifact only needs to update every time we update the JDT version
// so version it after the contained JDT release
version = '3.20.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    // "official" packaged version of Eclipse JDT
    // https://objectteams.wordpress.com/2017/01/09/eclipse-neon-2-is-on-maven-central/
    // https://bugs.eclipse.org/bugs/show_bug.cgi?id=484004
    implementation 'org.eclipse.jdt:org.eclipse.jdt.core:3.20.0'
}

// include dependencies from shadow configuration in compile tasks
tasks.withType(JavaCompile) {
    classpath += configurations.shadow
}

shadowJar {
    // exclude any remaining unused files from jar
    exclude 'about_files/**'
    exclude 'ant_tasks/**'
    exclude '*.profile'
    exclude '*.properties'
    exclude '.api_description'
    exclude '.options'
    exclude 'about.html'
    exclude 'jdtCompilerAdapter.jar'
    exclude 'plugin.xml'
    exclude 'profile.list'

    // relocate JDT and all its dependencies, may conflict as they are available in many artifacts
    // main reason: Android plugin includes org.eclipse.jdt.core.compiler:ecj which has conflicting JDT core packaged
    relocate 'org.eclipse', "${project.group}.eclipse"
    relocate 'org.apache', "${project.group}.apache"
    relocate 'org.osgi', "${project.group}.osgi"

    archiveClassifier = null // would default to "all"
}

// Make shadow jar the primary component for publishing
tasks.named('jar') {
    enabled = false
}

apply from: rootProject.file("gradle/publish.gradle")
